### PR TITLE
Move example sketch to examples folder

### PR DESCRIPTION
**Pull request by per1234**
This allows the example sketch to appear in the File > Examples >
XLR8LFSR menu.

### CODE REVIEW

**Comment by per1234** [comment]
@steve-superiontech @crakerbr-superiontech please let me know if there's anything I need to do to get this merged.

**Comment by per1234** [comment]
Duplicated by:
1. https://github.com/AloriumTechnology/XLR8LFSR/commit/f41971bfd8991f3fd264a5a6213fef5881ac3dcb
1. https://github.com/AloriumTechnology/XLR8LFSR/commit/74189258bb4d63e9bf149070b498057002970d1c
1. https://github.com/AloriumTechnology/XLR8LFSR/commit/22e4dbf1e0b954911abaa5273b35874b04d093b5
1. https://github.com/AloriumTechnology/XLR8LFSR/commit/8024123ecdcb6e765db071bab0b9e11121e1cc0b

Pretty sad that it took you 4 commits to do such a simple thing when you could have just clicked the "Merge" button on this pull request instead. And then I have to close the pull request myself because you didn't have the consideration to do so. I regret having made the effort to contribute to this project.

**Comment by steve-superiontech** [comment]
Bryan,


What is this about?




________________________________

**Comment by crakerbr-superiontech** [comment]
Unfortunately I was unaware of this merge request until I was forwarded this page in an email. It’s too bad, this would have been helpful information when I was learning the directory organization of Arduino, but as I said I didn’t see the original message and was unfamiliar with Github's request system. I thought that the messages were generated automatically informing me the Arduino structure was not correct, and didn't realize there was some open request that needed to be closed. I was unaware someone else was trying to make changes to the project.

**Pull request closed without merging**
